CREATE TABLE MARCA(
CODMARCA SERIAL PRIMARY KEY,
NOMEMARCA VARCHAR (80) NOT NULL UNIQUE
);

CREATE TABLE TIPO(
CODTIPO SERIAL PRIMARY  KEY,
NOMETIPO VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO(
CODPRODUTO SERIAL PRIMARY KEY,
NOMEPRODUTO VARCHAR (80) NOT NULL UNIQUE,
CODMARCA_FK INTEGER REFERENCES MARCA(CODMARCA) MATCH SIMPLE ON
DELETE CASCADE ON UPDATE CASCADE,
CODTIPO_FK INTEGER REFERENCES TIPO(CODTIPO) MATCH SIMPLE ON
DELETE CASCADE ON UPDATE CASCADE,
QUANTIDADE INTEGER NOT NULL,
VALORUNITARIO REAL NOT NULL
);

--MARCA
INSERT INTO MARCA(NOMEMARCA) VALUES ('NESTLE');
INSERT INTO MARCA(NOMEMARCA) VALUES ('LACTA');
INSERT INTO MARCA(NOMEMARCA) VALUES ('YOKI');
INSERT INTO MARCA(NOMEMARCA) VALUES ('KININO');
INSERT INTO MARCA(NOMEMARCA) VALUES ('COCA-COLA');
INSERT INTO MARCA(NOMEMARCA) VALUES ('QUALY');

ALTER TABLE MARCA ADD COLUMN DESCRICAO VARCHAR (80);
UPDATE MARCA SET DESCRICAO = 'CHOCOLATE' WHERE CODMARCA = 3;
UPDATE MARCA SET DESCRICAO = 'CHOCOLATE' WHERE CODMARCA = 4;
UPDATE MARCA SET DESCRICAO = 'CEREAL' WHERE CODMARCA = 5;
UPDATE MARCA SET DESCRICAO = 'CEREAL' WHERE CODMARCA = 6;
UPDATE MARCA SET DESCRICAO = 'REFRIGERANTE' WHERE CODMARCA = 7;
UPDATE MARCA SET DESCRICAO = 'LACTINIO' WHERE CODMARCA = 8;
SELECT * FROM MARCA;
--TORNAR A DESCRICAO OBRIGATORIA
ALTER TABLE MARCA ALTER COLUMN DESCRICAO SET NOT NULL;
------------------------------------------------------

--TIPO
INSERT INTO TIPO(NOMETIPO) VALUES ('ALIMENTICIOS');
INSERT INTO MARCA(NOMETIPO) VALUES ('');
INSERT INTO MARCA(NOMETIPO) VALUES ('YOKI');
INSERT INTO MARCA(NOMETIPO) VALUES ('KININO');

