CREATE TABLE MARCA(
CODMARCA SERIAL PRIMARY KEY,
NOMEMARCA VARCHAR (80) NOT NULL UNIQUE
);

CREATE TABLE TIPO(
CODTIPO SERIAL PRIMARY  KEY,
NOMETIPO VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO(
CODPRODUTO SERIAL PRIMARY KEY,
NOMEPRODUTO VARCHAR (80) NOT NULL UNIQUE,
CODMARCA_FK INTEGER REFERENCES MARCA(CODMARCA) MATCH SIMPLE ON
DELETE CASCADE ON UPDATE CASCADE,
CODTIPO_FK INTEGER REFERENCES TIPO(CODTIPO) MATCH SIMPLE ON
DELETE CASCADE ON UPDATE CASCADE,
QUANTIDADE INTEGER NOT NULL,
VALORUNITARIO REAL NOT NULL
);

--MARCA
INSERT INTO MARCA(NOMEMARCA) VALUES ('NESTLE');
INSERT INTO MARCA(NOMEMARCA) VALUES ('LACTA');
INSERT INTO MARCA(NOMEMARCA) VALUES ('ARISCO');
INSERT INTO MARCA(NOMEMARCA) VALUES ('KININO');
INSERT INTO MARCA(NOMEMARCA) VALUES ('COCA-COLA');
INSERT INTO MARCA(NOMEMARCA) VALUES ('QUALY');

ALTER TABLE MARCA ADD COLUMN DESCRICAO VARCHAR (80);
UPDATE MARCA SET DESCRICAO = 'CHOCOLATE' WHERE CODMARCA = 1;
UPDATE MARCA SET DESCRICAO = 'CHOCOLATE' WHERE CODMARCA = 2;
UPDATE MARCA SET DESCRICAO = 'ALIMENTICIO' WHERE CODMARCA = 3;
UPDATE MARCA SET DESCRICAO = 'ALIMENTICIO' WHERE CODMARCA = 4;
UPDATE MARCA SET DESCRICAO = 'REFRIGERANTE' WHERE CODMARCA = 5;
UPDATE MARCA SET DESCRICAO = 'LACTINIO' WHERE CODMARCA = 6;
SELECT * FROM MARCA;
--TORNAR A DESCRICAO OBRIGATORIA
ALTER TABLE MARCA ALTER COLUMN DESCRICAO SET NOT NULL;
------------------------------------------------------

--TIPO
INSERT INTO TIPO(NOMETIPO) VALUES ('ALIMENTICIOS');
INSERT INTO TIPO(NOMETIPO) VALUES ('REFRIGERANTE');
INSERT INTO TIPO(NOMETIPO) VALUES ('ENGRADADO');
INSERT INTO TIPO(NOMETIPO) VALUES ('DOCE');
SELECT * FROM TIPO;
--APAGAR 1 TIPO COM 'E'
DELETE FROM TIPO WHERE NOMETIPO LIKE 'E%';
--ATUALIZANDO 2 CAMPOS
UPDATE TIPO SET NOMETIPO = 'LIMPEZA' WHERE CODTIPO = 3;
UPDATE TIPO SET NOMETIPO = 'FRIOS' WHERE CODTIPO = 5;
--------------------------------------------------------

--PRODUTO
--CODTIPO = 2 ALIMENTICIOS
--CODMARCA = 3 ARISCO
--CODMARCA = 4 KININO
INSERT INTO PRODUTO(NOMEPRODUTO,CODMARCA_FK,CODTIPO_FK, QUANTIDADE,VALORUNITARIO) VALUES ('MAIONESE',3,2,30,21.18); --ARISCO

INSERT INTO PRODUTO(NOMEPRODUTO,CODMARCA_FK,CODTIPO_FK, QUANTIDADE,VALORUNITARIO) VALUES ('PIPOCA',4,2,20,8.70); --KININO

INSERT INTO PRODUTO(NOMEPRODUTO,CODMARCA_FK,CODTIPO_FK, QUANTIDADE,VALORUNITARIO) VALUES ('TEMPERO',3,2,55,14.99); --ARISCO

INSERT INTO PRODUTO(NOMEPRODUTO,CODMARCA_FK,CODTIPO_FK, QUANTIDADE,VALORUNITARIO) VALUES ('AMIDO DE MILHO',4,2,9,6.39); --KININO

INSERT INTO PRODUTO(NOMEPRODUTO,CODMARCA_FK,CODTIPO_FK, QUANTIDADE,VALORUNITARIO) VALUES ('BICARBONATO DE SODIO',4,2,60,16.60); --KININO

SELECT * FROM PRODUTO;
 --AUMENTAR 10%
UPDATE PRODUTO SET VALORUNITARIO  = VALORUNITARIO *0.1 WHERE CODTIPO_FK = 2;

--LISTE A QUANTIDADE DE PRODUTOS QUE SÃO DA MARCA ‘ARISCO’ E POSSUAM O 
--VALOR UNITÁRIO MAIOR QUE R$ 100,00

SELECT QUANTIDADE FROM PRODUTO WHERE CODMARCA_FK = 3 AND VALORUNITARIO > 100;

--MOSTRE O PRODUTO COM O MAIOR VALOR REGISTRADO;
SELECT * FROM PRODUTO ORDER BY VALORUNITARIO DESC;
--IMPRIMA OS DADOS DE TODOS OS PRODUTOS QUE COMECEM COM A LETRA ‘B’, 
--TENHAM A MARCA ‘KININO’ E SEJAM PRODUTOS ‘ALIMENTÍCIOS’;
SELECT * FROM PRODUTO WHERE NOMEPRODUTO LIKE 'B%' AND CODMARCA_FK = 4 AND CODTIPO_FK = 2;
--INFORME O VALOR TOTAL DE CADA ITEM REGISTRADO (VALORUNITÁRIO * 
--QUANTIDADE);
SELECT SUM((VALORUNITARIO * QUANTIDADE)) AS TOTAL FROM PRODUTO;
--INFORME O VALOR TOTAL EM ESTOQUE DA LOJA. (SOMA DE TODOS OS ELEMENTOS 
--DO EXERCÍCIO 8)
SELECT SUM(QUANTIDADE) FROM PRODUTO;



